const DEMO = {
  BLANK_LINK: "#!",
  companies: [
    {
      id: 1,
      companyName: "FAB",
    },
    {
      id: 2,
      companyName: "AFF",
    },
  ],
  users: [
    {
      id: 1,
      firstname: "Mark",
      lastname: "Otto",
      email: "admin@test.com",
      password: "admin@test.com",
      phone: "1231231231",
      companyId: 0,
      type: "1",
      status: 1,
    },
    {
      id: 2,
      firstname: "Jacob",
      lastname: "Thornton",
      email: "jacobthornton@test.com",
      password: "jacobthornton@test.com",
      phone: "1231231231",
      companyId: 1,
      type: "2",
      status: 1,
    },
    {
      id: 3,
      firstname: "Peter",
      lastname: "Jackson",
      email: "peterjackson@test.com",
      password: "peterjackson@test.com",
      phone: "1231231231",
      companyId: 1,
      type: "3",
      status: 1,
    },
    {
      id: 4,
      firstname: "Larry",
      lastname: "Bird",
      email: "larrybird@test.com",
      password: "larrybird@test.com",
      phone: "1231231231",
      companyId: 2,
      type: "2",
      status: 1,
    },
    {
      id: 5,
      firstname: "Thomas",
      lastname: "Muller",
      email: "thomasmuller@test.com",
      password: "thomasmuller@test.com",
      phone: "1231231231",
      companyId: 2,
      type: "3",
      status: 1,
    },
  ],
  deals: [
    {
      id: 1,
      companyId: 1,
      driverName: "Dennis Colman",
      driverPhone: "",
      truckPlate: "A1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-14 18:18:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 1,
    },
    {
      id: 2,
      companyId: 1,
      driverName: "Alex Millo",
      driverPhone: "",
      truckPlate: "B1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 2, //quantity based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 11:40:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 1,
    },
    {
      id: 3,
      companyId: 1,
      driverName: "Samuel Keullen",
      driverPhone: "",
      truckPlate: "C1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 16:10:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 2,
    },
    {
      id: 4,
      companyId: 1,
      driverName: "Thomas Jackson",
      driverPhone: "",
      truckPlate: "D1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 2, //quantity based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 12:51:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 2,
    },
    {
      id: 5,
      companyId: 1,
      driverName: "Jay Lancy",
      driverPhone: "",
      truckPlate: "E1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 13:11:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 3,
    },
    {
      id: 6,
      companyId: 2,
      driverName: "Jan Carlo",
      driverPhone: "",
      truckPlate: "F1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-14 18:18:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 1,
    },
    {
      id: 7,
      companyId: 2,
      driverName: "Thiago Silva",
      driverPhone: "",
      truckPlate: "G1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 2, //quantity based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 11:40:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 2,
    },
    {
      id: 8,
      companyId: 2,
      driverName: "Mirio Patrick",
      driverPhone: "",
      truckPlate: "H1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 16:10:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 2,
    },
    {
      id: 9,
      companyId: 2,
      driverName: "David Berlusconi",
      driverPhone: "",
      truckPlate: "I1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 2, //quantity based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 12:51:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 3,
    },
    {
      id: 10,
      companyId: 2,
      driverName: "Jet Gary",
      driverPhone: "",
      truckPlate: "J1234",
      trailerPlate: "",
      secondPlate: "",
      transporterId: 1,
      productType: 1, //weight based
      firstWeight: 0,
      secondWeight: 0,
      netWeight: 0,
      newNetWeight: 0,
      quantity: 0,
      newQuantity: 0,
      startedDateTime: "2020-12-15 13:11:23",
      alertTime: "",
      finishedDateTime: "",
      borderNumber: "",
      receiptNumber: "",
      description: "",
      newDescription: "",
      status: 3,
    },
  ],
  transporters: [
    {
      id: 1,
      transporter: "AAA",
    },
    {
      id: 2,
      transporter: "BBB",
    },
    {
      id: 3,
      transporter: "CCC",
    },
  ],
};

export default DEMO;
