const DEMO = {
  BLANK_LINK: "#!",
  companies: [
    {
      id: 1,
      companyName: "FAB",
    },
    {
      id: 2,
      companyName: "AFF",
    },
  ],
  users: [
    {
      id: 1,
      firstname: "Mark",
      lastname: "Otto",
      email: "admin@test.com",
      password: "admin@test.com",
      phone: "1231231231",
      companyId: 0,
      type: "1",
      status: 1,
    },
    {
      id: 2,
      firstname: "Jacob",
      lastname: "Thornton",
      email: "jacobthornton@test.com",
      password: "jacobthornton@test.com",
      phone: "1231231231",
      companyId: 1,
      type: "2",
      status: 1,
    },
    {
      id: 3,
      firstname: "Larry",
      lastname: "Bird",
      email: "larrybird@test.com",
      password: "larrybird@test.com",
      phone: "1231231231",
      companyId: 2,
      type: "3",
      status: 1,
    },
  ],
  deals: [
    {
      id: 1,
      driverName: "Dennis Colman",
      driverPhone: "",
      truckPlate: "A1234",
      trailerPlate: "",
      transporter: "",
      productType: 1, //weight based
      firstWeight: "",
      secondWeight: "",
      entryDateTime: "2020-12-14 18:18:23",
      alertTime: "",
      exitDateTime: "",
      description: "",
      status: "1",
    },
    {
      id: 2,
      driverName: "Alex Millo",
      driverPhone: "",
      truckPlate: "B1234",
      trailerPlate: "",
      transporter: "",
      productType: 2, //quantity based
      firstWeight: "",
      secondWeight: "",
      entryDateTime: "2020-12-15 11:40:23",
      alertTime: "",
      exitDateTime: "",
      description: "",
      status: "1",
    },
    {
      id: 3,
      driverName: "Samuel Keullen",
      driverPhone: "",
      truckPlate: "C1234",
      trailerPlate: "",
      transporter: "",
      productType: 1, //weight based
      firstWeight: "",
      secondWeight: "",
      entryDateTime: "2020-12-15 16:10:23",
      alertTime: "",
      exitDateTime: "",
      description: "",
      status: "2",
    },
    {
      id: 4,
      driverName: "Thomas Jackson",
      driverPhone: "",
      truckPlate: "D1234",
      trailerPlate: "",
      transporter: "",
      productType: 2, //quantity based
      firstWeight: "",
      secondWeight: "",
      entryDateTime: "2020-12-15 12:51:23",
      alertTime: "",
      exitDateTime: "",
      description: "",
      status: "2",
    },
    {
      id: 5,
      driverName: "Jay Lancy",
      driverPhone: "",
      truckPlate: "E1234",
      trailerPlate: "",
      transporter: "",
      productType: 1, //weight based
      firstWeight: "",
      secondWeight: "",
      entryDateTime: "2020-12-15 13:11:23",
      alertTime: "",
      exitDateTime: "",
      description: "",
      status: "3",
    },
  ],
};

export default DEMO;
